module simulate:
    snakefile: "simulate/simulate.smk"
    config: config

module classify:
    snakefile: "classify/classify.smk"
    config: config

use rule * from simulate as *

use rule * from classify as *

rule all:
    input:
        config["reads1"],
        config["reads2"]