module simulate:
    snakefile: "simulate/simulate.smk"
    config: config

if "gtdbtk" in config:
    module classify:
        snakefile: "classify/classify.smk"
        config: config

    use rule * from classify

use rule * from simulate

rule all:
    input:
        config["samples"]["reads1"],
        config["samples"]["reads2"]